#!/bin/bash
set -euo pipefail

RESULT=$(jq -n -c '{
  results: [
    {name: "CPUUtilization", title: "CPU utilization", unit: "percent"},
    {name: "DatabaseConnections", title: "Connections", unit: "count"},
    {name: "FreeableMemory", title: "Freeable memory", unit: "bytes"},
    {name: "VolumeBytesUsed", title: "Storage used", unit: "bytes"},
    {name: "OpcountersQuery", title: "Queries", unit: "count"}
  ] | map(. + {available_filters: [], available_group_by: []})
}')

echo "$RESULT"
